# Generated by Django 5.1.7 on 2025-04-02 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="processed_image",
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
